lib/slasher_web/router.ex
defmodule SlasherWeb.Router do
  use SlasherWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug SlasherWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SlasherWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController, only: [:index, :show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  scope "/slasher", SlasherWeb do
    pipe_through :browser

    get "/new", LinkController, :new
    get "/:id", LinkController, :show
    post "/", LinkController, :create
  end
end

lib/slasher/urls/link.ex
defmodule Slasher.Urls.Link do
  @moduledoc """
  Stores the long_url and it's short_url.
  Every long_url and short_url it's associated with the user
  that created the link.
  Date stores information about Day/Month/Year that was created the link.
  """
  use Ecto.Schema
  import Ecto.Changeset
  alias Slasher.SlasherCode
  alias __MODULE__

  schema "links" do
    field :date, :string
    field :long_url, :string
    field :short_url, :string
    belongs_to :user, Slasher.Accounts.User

    timestamps()
  end

  @required_fields ~w(long_url user_id)a

  def new do
    cast(%Link{}, %{}, [])
  end

  @doc """
  Changeset that validates the required fields and calls the shorten
  function to create a short_url to the long_url.
  """

  def changeset(link, attrs) do
    changeset =
      link
      |> cast(attrs, [@required_fields])
      |> validate_required([@required_fields])

    changeset =
      case get_field(changeset, :long_url) do
        nil -> changeset
        long_url -> change(changeset, %{short_url: SlasherCode.shorten(long_url)})
      end

    changeset
    |> unique_constraint(:short_url)
    |> validate_url(:long_url)
  end

  defp validate_url(changeset, field) do
    validate_change(changeset, field, fn field, long_url ->
      case :http_uri.parse(String.to_charlist(long_url)) do
        {:ok, _} -> []
        {:error, _} -> [{field, "Sorry, this is not a valid Url."}]
      end
    end)
  end
end

lib/slasher_web/controllers/link_controller.ex
defmodule SlasherWeb.LinkController do
  use SlasherWeb, :controller

  alias Slasher.Repo
  alias Slasher.Urls.Link
  alias Slasher.Urls
  alias Slasher.SlasherCode

  def new(conn, _params) do
    changeset = Link.new()
    render(conn, "new.html", changeset: changeset)
  end

  def index(conn, _params) do
    links = Urls.list_link!()
    render(conn, "index.html", links: links)
  end

  def get_long_url(conn, %{"id" => short_url}) do
    case lengthen(short_url) do
      {:error, _} ->
        put_status(conn, :not_found)
        |> text("Not found")

      {:ok, long_url} ->
        redirect(conn, external: long_url)
    end
  end

  def make_short_url(conn, %{"url" => long_url}) do
    short_url = SlasherCode.shorten(long_url)

    put_resp_header(conn, "location", short_url)
    |> put_status(:created)
    |> text("")
  end

  def show(conn, %{"id" => short_url}) do
    link = Repo.get(Link, short_url)
    render(conn, "show.html", link: link)
  end

  def delete_short_url(conn, %{"slashercode" => short_url}) do
    case Repo.get_by(Link, short_url: short_url) do
      nil ->
        {:error, "Not found"}

      url ->
        Repo.delete!(url)
        :ok
    end

    render(conn, "index.html")
  end

  def lengthen(short_url) do
    case Repo.get_by(Link, short_url: short_url) do
      nil ->
        {:error, "Not found"}

      url ->
        {:ok, url.long_url}
    end
  end
end

lib/slasher_web/views/link_view.ex
defmodule SlasherWeb.LinkView do
  use SlasherWeb, :view
end

lib/slasher_web/templates/link/edit.html.eex
<h1>Edit Link</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.link_path(@conn, :update, @link)) %>

<span><%= link "Back", to: Routes.link_path(@conn, :index) %></span>

lib/slasher_web/templates/link/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :long_url %>
  <%= text_input f, :long_url %>
  <%= error_tag f, :long_url %>

  <%= label f, :short_url %>
  <%= text_input f, :short_url %>
  <%= error_tag f, :short_url %>

  <%= label f, :date %>
  <%= text_input f, :date %>
  <%= error_tag f, :date %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

lib/slasher_web/templates/link/index.html.eex
<h1>Listing Link</h1>

<table>
  <thead>
    <tr>
      <th>Long url</th>
      <th>Short url</th>
      <th>Date</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for link <- @links do %>
    <tr>
      <td><%= link.long_url %></td>
      <td><%= link.short_url %></td>
      <td><%= link.date %></td>

      <td>
        <%= link "Show", to: Routes.link_path(@conn, :show, link) %>
        <%= link "Edit", to: Routes.link_path(@conn, :edit, link) %>
        <%= link "Delete", to: Routes.link_path(@conn, :delete, link), method: :delete, data: [confirm: "Are you sure?"] %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Link", to: Routes.link_path(@conn, :new) %></span>

lib/slasher_web/templates/link/new.html.eex
<h1>New Link</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.link_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.link_path(@conn, :index) %></span>

lib/slasher_web/templates/link/show.html.eex
<h1>Show Link</h1>

<ul>

  <li>
    <strong>Long url:</strong>
    <%= @link.long_url %>
  </li>

  <li>
    <strong>Short url:</strong>
    <%= @link.short_url %>
  </li>

  <li>
    <strong>Date:</strong>
    <%= @link.date %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.link_path(@conn, :edit, @link) %></span>
<span><%= link "Back", to: Routes.link_path(@conn, :index) %></span>