lib/slasher_web/router.ex
defmodule SlasherWeb.Router do
  use SlasherWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug SlasherWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SlasherWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController, only: [:index, :show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  scope "/slasher", SlasherWeb do
    pipe_through :browser

    get "/new", LinkController, :new
    get "/:id", LinkController, :show
    post "/", LinkController, :create
  end
end

lib/slasher_web/templates/page/index.html.eex
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Slash!</title>
    </head>
    <body>
        <section class="phx-hero">
            <h1><%= gettext "Welcome to %{name}!", name: "Slash!" %></h1>
            <p>Slash is an URL shortener!<br/><%= link "Sign up ", to: Routes.user_path(@conn, :new) %>or
                <%= link "Login ", to: Routes.session_path(@conn, :new) %>to shorten your URLs.</p>
        </section>
    </body>
</html>

<section class= "center">
  <p>Built with <a href="https://github.com/elixir-lang/elixir">Elixir 1.8.1</a>
  and <a href="https://github.com/phoenixframework/phoenix">Phoenix 1.4.1</a> </p>
</section>